# Configuração do Netlify para aplicação React com Vite

[build]
  # Diretório onde o comando de build será executado
  base = "/"
  
  # Comando para construir o site
  command = "npm run build"
  
  # Diretório que será publicado (output do build)
  publish = "dist"

# Configurações para SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configurações de ambiente de produção
[build.environment]
  NODE_VERSION = "18"

# Headers para melhorar a segurança e performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:;" 